version: '2.1'

services:
  keycloak-postgres:
    container_name: keycloak-postgres
    restart: unless-stopped
    image: postgres:15-alpine
    hostname: keycloak-postgres
    ports:
      - '9010:5432'
    environment:
      POSTGRES_DB: keycloak
      POSTGRES_USER: keycloak
      POSTGRES_PASSWORD: keycloak
      POSTGRES_HOST: keycloak-postgres
    volumes:
      - keycloak_postgres_data:/var/lib/postgresql/data
    networks:
      - keycloak-network

  keycloak-server:
    container_name: keycloak-server
    restart: unless-stopped
    image: jboss/keycloak:16.1.1
    hostname: keycloak-server
    ports:
      - '9011:8080'
    env_file:
      - keycloak/.env
    networks:
      - keycloak-network
    depends_on:
      - keycloak-postgres

networks:
  keycloak-network:
    name: keycloak-network

volumes:
  keycloak_postgres_data:
    name: keycloak_postgres_data
    driver: local