# docker-compose.base.yml
version: '2.4'

services:
  keycloak-server:
    container_name: keycloak-server
    hostname: keycloak-server
    restart: unless-stopped
    image: quay.io/keycloak/keycloak:20.0.1
    ports:
      - '9011:8080'
    environment:
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin