version: '3.9'

services:
  minio-server:
    container_name: minio-server
    restart: unless-stopped
    image: bitnami/minio:2022.10.29 # minio/minio:RELEASE.2022-10-29T06-21-33Z
    hostname: minio-server
    ports:
      - '9000:9000'
      - '9001:9001'
    environment:
      MINIO_ROOT_USER: admin
      MINIO_ROOT_PASSWORD: admin_pass
      MINIO_DEFAULT_BUCKETS: test-bucket
    #command: server /data --console-address ":9001"
    volumes:
      - minio_storage:/data

volumes:
  minio_storage:
    name: minio_storage
    driver: local