version: '3.9'

services:
  minio-server:
    container_name: minio-server
    restart: unless-stopped
    image: bitnami/minio:2022.10.29
    hostname: minio-server
    ports:
      - '9020:9000'
      - '9021:9001'
    environment:
      MINIO_ROOT_USER: admin
      MINIO_ROOT_PASSWORD: admin123
      MINIO_DEFAULT_BUCKETS: test-bucket
    volumes:
      - minio_storage:/data

volumes:
  minio_storage:
    name: minio_storage
    driver: local